### ISSUE TITLE
play-router-annotations doesn't work with Play 2.1

### ISSUE THREAD

**Issue by lukehutch** [digiPlant/play-router-annotations#9]
I can't get play-router-annotations to work with Play 2.1.

I put the following dependency into my Build.scala file:

```
  "com.google.code.maven-play-plugin.org.playframework.modules.router" % "play-router" % "1.2"
```

(version 1.3 isn't available in the maven repository yet).

It finds the plugin, but gives me the following error message at runtime:

play.api.PlayException: Cannot load plugin[Plugin [play.modules.router.RouterAnnotationsPlugin] cannot been instantiated.]
    at play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:156) ~[play_2.10.jar:2.1.0]
    at play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:130) ~[play_2.10.jar:2.1.0]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:309) ~[scala-library.jar:na]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
Caused by: java.lang.NoClassDefFoundError: play/PlayPlugin
    at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_10]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791) ~[na:1.7.0_10]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_10]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_10]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_10]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_10]
Caused by: java.lang.ClassNotFoundException: play.PlayPlugin
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_10]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_10]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_10]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_10]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[na:1.7.0_10]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[na:1.7.0_10]
